before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
  - sudo apt-get install debian-keyring debian-archive-keyring
  - sudo apt-key update
  - sudo apt-get update
  - sudo apt-get install libboost1.55-all-dev g++-4.8

install: true

language: cpp

compiler:
  - clang
  - gcc-4.8

script: make && make -C tests
