dist: bionic

before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic main"
  - sudo apt-get install debian-keyring debian-archive-keyring
  - sudo apt-key update
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev libstdc++-8-dev
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-da language-pack-nl
  - sudo apt-get install libboost-tools-dev xsltproc doxygen docbook-xsl default-jdk fop

install: true

language: cpp

compiler: clang

script: ./configure && make && make test && make install
