language: cpp

os:
  - linux
  - osx

dist: focal

osx_image: xcode12

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
      - language-pack-en
      - language-pack-da
      - language-pack-nl
      - libboost-tools-dev
      - xsltproc
      - doxygen
      - docbook-xsl
      - default-jdk
      - fop

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost; fi

script:
  - ./configure
  - make
  - sudo make install

jobs:
  allow_failures:
    - os: osx

